_target_: merge.CityModelMerger

data_dir: '/Users/zhaiyu/Workspace/inpaint-utils/data/merge'
temp_dir: '/Users/zhaiyu/Workspace/inpaint-utils/data/temp'
output_dir: '/Users/zhaiyu/Workspace/inpaint-utils/data/output'

prefix_ahn4: 'ahn4_'
prefix_ahn34: 'ahn34_'

do_append_id: true

changed_ids: '/Users/zhaiyu/Workspace/inpaint-utils/data/merge/changed.txt'
changed_temp: ${merge.temp_dir}/changed.txt
