defaults:
  - clean: default
  - compare: default
  - db: [godzilla, url]
  - mask: default
  - split: default
  - merge: default
  - overlay: default

  - device: macbook

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
