defaults:
  - device: macbook
  - clean: default
  - compare: default
  - download: [db, ahn]
  - mask: default
  - split: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
