input_dir: '/Users/zhaiyu/Downloads/ahn4_ams_res25cm50cm'
output_dir: '/Users/zhaiyu/Downloads/ahn4_ams_res25cm50cm_trainvaltest'
suffix: '.tif'
train: []  # remaining tiles from validation if empty
val: [335, 1609, 1629, 1658, 4221, 4228, 4268, 4282, 4298, 4343, 4365, 7099, 7112, 7185, 7200, 7222, 7248]
test: null  # all buildings with no-data pixels
